<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Cline\Struct\Attributes\AbstractGeneratedValueAttribute;
use Cline\Struct\Attributes\AbstractStringTransformer;
use Cline\Struct\Attributes\After;
use Cline\Struct\Attributes\AfterLast;
use Cline\Struct\Attributes\Ascii;
use Cline\Struct\Attributes\Before;
use Cline\Struct\Attributes\BeforeLast;
use Cline\Struct\Attributes\Between;
use Cline\Struct\Attributes\BetweenFirst;
use Cline\Struct\Attributes\CamelCase;
use Cline\Struct\Attributes\ChopEnd;
use Cline\Struct\Attributes\ChopStart;
use Cline\Struct\Attributes\Deduplicate;
use Cline\Struct\Attributes\Finish;
use Cline\Struct\Attributes\Headline;
use Cline\Struct\Attributes\KebabCase;
use Cline\Struct\Attributes\LeftTrim;
use Cline\Struct\Attributes\Limit;
use Cline\Struct\Attributes\Lowercase;
use Cline\Struct\Attributes\Mask;
use Cline\Struct\Attributes\Numbers;
use Cline\Struct\Attributes\PadBoth;
use Cline\Struct\Attributes\PadLeft;
use Cline\Struct\Attributes\PadRight;
use Cline\Struct\Attributes\PascalCase;
use Cline\Struct\Attributes\Password;
use Cline\Struct\Attributes\Random;
use Cline\Struct\Attributes\Repeat;
use Cline\Struct\Attributes\Replace;
use Cline\Struct\Attributes\ReplaceEnd;
use Cline\Struct\Attributes\ReplaceFirst;
use Cline\Struct\Attributes\ReplaceLast;
use Cline\Struct\Attributes\ReplaceStart;
use Cline\Struct\Attributes\Reverse;
use Cline\Struct\Attributes\RightTrim;
use Cline\Struct\Attributes\Slug;
use Cline\Struct\Attributes\SnakeCase;
use Cline\Struct\Attributes\Squish;
use Cline\Struct\Attributes\Start;
use Cline\Struct\Attributes\Strings\AbstractGeneratedValueAttribute as StringsAbstractGeneratedValueAttribute;
use Cline\Struct\Attributes\Strings\AbstractStringTransformer as StringsAbstractStringTransformer;
use Cline\Struct\Attributes\Strings\After as StringsAfter;
use Cline\Struct\Attributes\Strings\AfterLast as StringsAfterLast;
use Cline\Struct\Attributes\Strings\Ascii as StringsAscii;
use Cline\Struct\Attributes\Strings\Before as StringsBefore;
use Cline\Struct\Attributes\Strings\BeforeLast as StringsBeforeLast;
use Cline\Struct\Attributes\Strings\Between as StringsBetween;
use Cline\Struct\Attributes\Strings\BetweenFirst as StringsBetweenFirst;
use Cline\Struct\Attributes\Strings\CamelCase as StringsCamelCase;
use Cline\Struct\Attributes\Strings\ChopEnd as StringsChopEnd;
use Cline\Struct\Attributes\Strings\ChopStart as StringsChopStart;
use Cline\Struct\Attributes\Strings\Deduplicate as StringsDeduplicate;
use Cline\Struct\Attributes\Strings\Finish as StringsFinish;
use Cline\Struct\Attributes\Strings\Headline as StringsHeadline;
use Cline\Struct\Attributes\Strings\KebabCase as StringsKebabCase;
use Cline\Struct\Attributes\Strings\LeftTrim as StringsLeftTrim;
use Cline\Struct\Attributes\Strings\Limit as StringsLimit;
use Cline\Struct\Attributes\Strings\Lowercase as StringsLowercase;
use Cline\Struct\Attributes\Strings\Mask as StringsMask;
use Cline\Struct\Attributes\Strings\Numbers as StringsNumbers;
use Cline\Struct\Attributes\Strings\PadBoth as StringsPadBoth;
use Cline\Struct\Attributes\Strings\PadLeft as StringsPadLeft;
use Cline\Struct\Attributes\Strings\PadRight as StringsPadRight;
use Cline\Struct\Attributes\Strings\PascalCase as StringsPascalCase;
use Cline\Struct\Attributes\Strings\Password as StringsPassword;
use Cline\Struct\Attributes\Strings\Random as StringsRandom;
use Cline\Struct\Attributes\Strings\Repeat as StringsRepeat;
use Cline\Struct\Attributes\Strings\Replace as StringsReplace;
use Cline\Struct\Attributes\Strings\ReplaceEnd as StringsReplaceEnd;
use Cline\Struct\Attributes\Strings\ReplaceFirst as StringsReplaceFirst;
use Cline\Struct\Attributes\Strings\ReplaceLast as StringsReplaceLast;
use Cline\Struct\Attributes\Strings\ReplaceStart as StringsReplaceStart;
use Cline\Struct\Attributes\Strings\Reverse as StringsReverse;
use Cline\Struct\Attributes\Strings\RightTrim as StringsRightTrim;
use Cline\Struct\Attributes\Strings\Slug as StringsSlug;
use Cline\Struct\Attributes\Strings\SnakeCase as StringsSnakeCase;
use Cline\Struct\Attributes\Strings\Squish as StringsSquish;
use Cline\Struct\Attributes\Strings\Start as StringsStart;
use Cline\Struct\Attributes\Strings\StudlyCase as StringsStudlyCase;
use Cline\Struct\Attributes\Strings\Take as StringsTake;
use Cline\Struct\Attributes\Strings\Titlecase as StringsTitlecase;
use Cline\Struct\Attributes\Strings\Transliterate as StringsTransliterate;
use Cline\Struct\Attributes\Strings\Trim as StringsTrim;
use Cline\Struct\Attributes\Strings\Ulid as StringsUlid;
use Cline\Struct\Attributes\Strings\Unwrap as StringsUnwrap;
use Cline\Struct\Attributes\Strings\Uppercase as StringsUppercase;
use Cline\Struct\Attributes\Strings\Uuid as StringsUuid;
use Cline\Struct\Attributes\Strings\Words as StringsWords;
use Cline\Struct\Attributes\Strings\Wrap as StringsWrap;
use Cline\Struct\Attributes\StudlyCase;
use Cline\Struct\Attributes\Take;
use Cline\Struct\Attributes\Titlecase;
use Cline\Struct\Attributes\Transliterate;
use Cline\Struct\Attributes\Trim;
use Cline\Struct\Attributes\Ulid;
use Cline\Struct\Attributes\Unwrap;
use Cline\Struct\Attributes\Uppercase;
use Cline\Struct\Attributes\Uuid;
use Cline\Struct\Attributes\Words;
use Cline\Struct\Attributes\Wrap;

class_alias(StringsAbstractStringTransformer::class, AbstractStringTransformer::class);
class_alias(StringsAbstractGeneratedValueAttribute::class, AbstractGeneratedValueAttribute::class);
class_alias(StringsAfter::class, After::class);
class_alias(StringsAfterLast::class, AfterLast::class);
class_alias(StringsAscii::class, Ascii::class);
class_alias(StringsBefore::class, Before::class);
class_alias(StringsBeforeLast::class, BeforeLast::class);
class_alias(StringsBetween::class, Between::class);
class_alias(StringsBetweenFirst::class, BetweenFirst::class);
class_alias(StringsCamelCase::class, CamelCase::class);
class_alias(StringsChopEnd::class, ChopEnd::class);
class_alias(StringsChopStart::class, ChopStart::class);
class_alias(StringsDeduplicate::class, Deduplicate::class);
class_alias(StringsFinish::class, Finish::class);
class_alias(StringsHeadline::class, Headline::class);
class_alias(StringsKebabCase::class, KebabCase::class);
class_alias(StringsLeftTrim::class, LeftTrim::class);
class_alias(StringsLimit::class, Limit::class);
class_alias(StringsLowercase::class, Lowercase::class);
class_alias(StringsMask::class, Mask::class);
class_alias(StringsNumbers::class, Numbers::class);
class_alias(StringsPadBoth::class, PadBoth::class);
class_alias(StringsPadLeft::class, PadLeft::class);
class_alias(StringsPadRight::class, PadRight::class);
class_alias(StringsPascalCase::class, PascalCase::class);
class_alias(StringsPassword::class, Password::class);
class_alias(StringsRandom::class, Random::class);
class_alias(StringsRepeat::class, Repeat::class);
class_alias(StringsReplace::class, Replace::class);
class_alias(StringsReplaceEnd::class, ReplaceEnd::class);
class_alias(StringsReplaceFirst::class, ReplaceFirst::class);
class_alias(StringsReplaceLast::class, ReplaceLast::class);
class_alias(StringsReplaceStart::class, ReplaceStart::class);
class_alias(StringsReverse::class, Reverse::class);
class_alias(StringsRightTrim::class, RightTrim::class);
class_alias(StringsSlug::class, Slug::class);
class_alias(StringsSnakeCase::class, SnakeCase::class);
class_alias(StringsSquish::class, Squish::class);
class_alias(StringsStart::class, Start::class);
class_alias(StringsStudlyCase::class, StudlyCase::class);
class_alias(StringsTake::class, Take::class);
class_alias(StringsTitlecase::class, Titlecase::class);
class_alias(StringsTransliterate::class, Transliterate::class);
class_alias(StringsTrim::class, Trim::class);
class_alias(StringsUlid::class, Ulid::class);
class_alias(StringsUnwrap::class, Unwrap::class);
class_alias(StringsUppercase::class, Uppercase::class);
class_alias(StringsUuid::class, Uuid::class);
class_alias(StringsWords::class, Words::class);
class_alias(StringsWrap::class, Wrap::class);
