<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Cline\Struct\Metadata\ClassMetadata;
use Cline\Struct\Metadata\PropertyMetadata;
use Illuminate\Support\LazyCollection;
use Tests\Fixtures\Data\MappedUserData;

describe('ClassMetadata', function (): void {
    test('builds an input name lookup for fast membership checks', function (): void {
        // Arrange
        $reflection = new ReflectionClass(MappedUserData::class);
        $parameter = $reflection->getConstructor()->getParameters()[0];

        $metadata = new ClassMetadata(
            class: MappedUserData::class,
            reflection: $reflection,
            properties: [
                'id' => new PropertyMetadata(
                    name: 'id',
                    inputName: 'identifier',
                    outputName: 'id',
                    types: ['int'],
                    typeKinds: ['int'],
                    nullable: false,
                    hasDefaultValue: false,
                    defaultValue: null,
                    replaceEmptyStringsWithNull: false,
                    inferValidationRules: false,
                    isOptional: false,
                    isSensitive: false,
                    isEncrypted: false,
                    isComputed: false,
                    hasCollectionResultAttribute: false,
                    hasCollectionSourceAttribute: false,
                    isLazy: false,
                    computer: null,
                    lazyResolver: null,
                    lazyGroups: [],
                    includeConditions: [],
                    excludeConditions: [],
                    castClass: null,
                    cast: null,
                    dataListType: null,
                    dataListCastClass: null,
                    dataListCast: null,
                    dataCollectionType: null,
                    dataListTypeKind: null,
                    dataCollectionCastClass: null,
                    dataCollectionCast: null,
                    dataCollectionTypeKind: null,
                    hasCollectionItemCast: false,
                    validationRules: [],
                    itemValidationRules: [],
                    parameter: $parameter,
                    property: null,
                ),
            ],
            forbidUndefinedValues: false,
            forbidSuperfluousKeys: true,
            inferValidationRules: false,
            validatorMutator: null,
            requestPayloadResolver: null,
            modelPayloadResolver: null,
            stringifier: null,
            factory: null,
        );

        // Assert
        expect($metadata->inputNameLookup)->toBe([
            'identifier' => true,
        ])->and($metadata->hydratedPropertyLookup)->toBe([
            'id' => true,
        ])->and($metadata->hydratedProperties)->toHaveCount(1)
            ->and($metadata->defaultProjectionProperties)->toBe([$metadata->properties['id']])
            ->and($metadata->defaultProjectionPropertiesWithoutSensitive)->toBe([$metadata->properties['id']])
            ->and($metadata->computedProperties)->toBe([])
            ->and($metadata->computedInputNamesFor('id'))->toBe([]);
    });

    test('derives computed input names from hydrated properties', function (): void {
        $reflection = new ReflectionClass(MappedUserData::class);
        $parameter = $reflection->getConstructor()->getParameters()[0];

        $metadata = new ClassMetadata(
            class: MappedUserData::class,
            reflection: $reflection,
            properties: [
                'firstName' => new PropertyMetadata(
                    name: 'firstName',
                    inputName: 'firstName',
                    outputName: 'firstName',
                    types: ['string'],
                    typeKinds: ['string'],
                    nullable: false,
                    hasDefaultValue: false,
                    defaultValue: null,
                    replaceEmptyStringsWithNull: false,
                    inferValidationRules: false,
                    isOptional: false,
                    isSensitive: false,
                    isEncrypted: false,
                    isComputed: false,
                    hasCollectionResultAttribute: false,
                    hasCollectionSourceAttribute: false,
                    isLazy: false,
                    computer: null,
                    lazyResolver: null,
                    lazyGroups: [],
                    includeConditions: [],
                    excludeConditions: [],
                    castClass: null,
                    cast: null,
                    dataListType: null,
                    dataListCastClass: null,
                    dataListCast: null,
                    dataCollectionType: null,
                    dataListTypeKind: null,
                    dataCollectionCastClass: null,
                    dataCollectionCast: null,
                    dataCollectionTypeKind: null,
                    hasCollectionItemCast: false,
                    validationRules: [],
                    itemValidationRules: [],
                    parameter: $parameter,
                    property: null,
                ),
                'lastName' => new PropertyMetadata(
                    name: 'lastName',
                    inputName: 'lastName',
                    outputName: 'lastName',
                    types: ['string'],
                    typeKinds: ['string'],
                    nullable: false,
                    hasDefaultValue: false,
                    defaultValue: null,
                    replaceEmptyStringsWithNull: false,
                    inferValidationRules: false,
                    isOptional: false,
                    isSensitive: false,
                    isEncrypted: false,
                    isComputed: false,
                    hasCollectionResultAttribute: false,
                    hasCollectionSourceAttribute: false,
                    isLazy: false,
                    computer: null,
                    lazyResolver: null,
                    lazyGroups: [],
                    includeConditions: [],
                    excludeConditions: [],
                    castClass: null,
                    cast: null,
                    dataListType: null,
                    dataListCastClass: null,
                    dataListCast: null,
                    dataCollectionType: null,
                    dataListTypeKind: null,
                    dataCollectionCastClass: null,
                    dataCollectionCast: null,
                    dataCollectionTypeKind: null,
                    hasCollectionItemCast: false,
                    validationRules: [],
                    itemValidationRules: [],
                    parameter: $parameter,
                    property: null,
                ),
                'fullName' => new PropertyMetadata(
                    name: 'fullName',
                    inputName: 'fullName',
                    outputName: 'fullName',
                    types: ['string'],
                    typeKinds: ['string'],
                    nullable: false,
                    hasDefaultValue: false,
                    defaultValue: null,
                    replaceEmptyStringsWithNull: false,
                    inferValidationRules: false,
                    isOptional: false,
                    isSensitive: false,
                    isEncrypted: false,
                    isComputed: true,
                    hasCollectionResultAttribute: false,
                    hasCollectionSourceAttribute: false,
                    isLazy: false,
                    computer: null,
                    lazyResolver: null,
                    lazyGroups: [],
                    includeConditions: [],
                    excludeConditions: [],
                    castClass: null,
                    cast: null,
                    dataListType: null,
                    dataListCastClass: null,
                    dataListCast: null,
                    dataCollectionType: null,
                    dataListTypeKind: null,
                    dataCollectionCastClass: null,
                    dataCollectionCast: null,
                    dataCollectionTypeKind: null,
                    hasCollectionItemCast: false,
                    validationRules: [],
                    itemValidationRules: [],
                    parameter: $parameter,
                    property: null,
                ),
            ],
            forbidUndefinedValues: false,
            forbidSuperfluousKeys: true,
            inferValidationRules: false,
            validatorMutator: null,
            requestPayloadResolver: null,
            modelPayloadResolver: null,
            stringifier: null,
            factory: null,
        );

        expect($metadata->computedInputNamesFor('fullName'))->toBe(['firstName', 'lastName'])
            ->and($metadata->computedInputNamesFor('firstName'))->toBe(['lastName'])
            ->and($metadata->computedInputNamesFor('missing'))->toBe([])
            ->and($metadata->computedInputNames)->toBe([
                'fullName' => ['firstName', 'lastName'],
            ]);
    });

    test('tracks only properties that need post-hydration collection passes', function (): void {
        $reflection = new ReflectionClass(MappedUserData::class);
        $parameter = $reflection->getConstructor()->getParameters()[0];

        $plain = new PropertyMetadata(
            name: 'plain',
            inputName: 'plain',
            outputName: 'plain',
            types: ['string'],
            typeKinds: ['string'],
            nullable: false,
            hasDefaultValue: false,
            defaultValue: null,
            replaceEmptyStringsWithNull: false,
            inferValidationRules: false,
            isOptional: false,
            isSensitive: false,
            isEncrypted: false,
            isComputed: false,
            hasCollectionResultAttribute: false,
            hasCollectionSourceAttribute: false,
            isLazy: false,
            computer: null,
            lazyResolver: null,
            lazyGroups: [],
            includeConditions: [],
            excludeConditions: [],
            castClass: null,
            cast: null,
            dataListType: null,
            dataListCastClass: null,
            dataListCast: null,
            dataCollectionType: null,
            dataListTypeKind: null,
            dataCollectionCastClass: null,
            dataCollectionCast: null,
            dataCollectionTypeKind: null,
            hasCollectionItemCast: false,
            validationRules: [],
            itemValidationRules: [],
            parameter: $parameter,
            property: null,
        );

        $lazyCollection = new PropertyMetadata(
            name: 'lazyCollection',
            inputName: 'lazyCollection',
            outputName: 'lazyCollection',
            types: [LazyCollection::class],
            typeKinds: ['other'],
            nullable: false,
            hasDefaultValue: false,
            defaultValue: null,
            replaceEmptyStringsWithNull: false,
            inferValidationRules: false,
            isOptional: false,
            isSensitive: false,
            isEncrypted: false,
            isComputed: false,
            hasCollectionResultAttribute: false,
            hasCollectionSourceAttribute: false,
            isLazy: false,
            computer: null,
            lazyResolver: null,
            lazyGroups: [],
            includeConditions: [],
            excludeConditions: [],
            castClass: null,
            cast: null,
            dataListType: null,
            dataListCastClass: null,
            dataListCast: null,
            dataCollectionType: null,
            dataListTypeKind: null,
            dataCollectionCastClass: null,
            dataCollectionCast: null,
            dataCollectionTypeKind: null,
            hasCollectionItemCast: false,
            validationRules: [],
            itemValidationRules: [],
            parameter: $parameter,
            property: null,
            lazyLaravelCollectionType: 'string',
        );

        $generatedLazyCollection = new PropertyMetadata(
            name: 'generatedLazyCollection',
            inputName: 'generatedLazyCollection',
            outputName: 'generatedLazyCollection',
            types: [LazyCollection::class],
            typeKinds: ['other'],
            nullable: false,
            hasDefaultValue: false,
            defaultValue: null,
            replaceEmptyStringsWithNull: false,
            inferValidationRules: false,
            isOptional: false,
            isSensitive: false,
            isEncrypted: false,
            isComputed: true,
            hasCollectionResultAttribute: false,
            hasCollectionSourceAttribute: true,
            isLazy: false,
            computer: null,
            lazyResolver: null,
            lazyGroups: [],
            includeConditions: [],
            excludeConditions: [],
            castClass: null,
            cast: null,
            dataListType: null,
            dataListCastClass: null,
            dataListCast: null,
            dataCollectionType: null,
            dataListTypeKind: null,
            dataCollectionCastClass: null,
            dataCollectionCast: null,
            dataCollectionTypeKind: null,
            hasCollectionItemCast: false,
            validationRules: [],
            itemValidationRules: [],
            parameter: $parameter,
            property: null,
            lazyLaravelCollectionType: 'string',
        );

        $metadata = new ClassMetadata(
            class: MappedUserData::class,
            reflection: $reflection,
            properties: [
                'plain' => $plain,
                'lazyCollection' => $lazyCollection,
                'generatedLazyCollection' => $generatedLazyCollection,
            ],
            forbidUndefinedValues: false,
            forbidSuperfluousKeys: true,
            inferValidationRules: false,
            validatorMutator: null,
            requestPayloadResolver: null,
            modelPayloadResolver: null,
            stringifier: null,
            factory: null,
        );

        expect($metadata->postHydrationProperties)->toBe([$lazyCollection])
            ->and($metadata->postHydrationCollectionSourceProperties)->toBe([$generatedLazyCollection]);
    });
});
